name:                server
version:             0.1.0.0
github:              "https://github.com/dnulnets/heat"
license:             BSD3
author:              "Tomas Stenlund"
maintainer:          "tomas.stenlund@telia.com"
copyright:           "2019 Tomas Stenlund"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at https://github.com/dnulnets/heat

dependencies:
- base >= 4.7 && < 5
- text
- yesod
- yesod-auth
- http-types
- wai
- wai-cors
- wai-extra
- containers
- jwt
- aeson
- time
- persistent
- persistent-template
- persistent-postgresql
- yesod-core
- http-conduit
- fast-logger
- monad-logger
- bytestring
- cryptonite
- strings
- warp
- data-default-class
- hexstring

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
