apiVersion: apps/v1
kind: Deployment
metadata:
  name: prmbldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prmbldb
  template:
    metadata:
      labels:
        app: prmbldb
    spec:
      containers:
        - name: prmbldb-container
          image: localhost:32000/prmbldb
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: prmbldb
      volumes:
        - name: prmbldb
          persistentVolumeClaim:
            claimName: prmbldb-pv-claim
